version: "3"
# networks:
#   zeng-fan-cli:
services:
  editor-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: editor-server # 依赖于当前 Dockerfile 创建镜像
    container_name: editor-server
    # networks:
    #   - zeng-fan-cli
    ports:
      - 8081:3311 # 宿主机通过 8081 访问
  editor-redis:
    image: redis # 引用官网 redis 镜像
    container_name: editor-redis
    # networks:
    #   - zeng-fan-cli
    ports:
      - 6378:6379 # 宿主机可以用 127.0.0.1:6378 即可连接容器中的数据库
    environment:
      - TZ=Asia/Shanghai # 设置时区
